[features]
seeds = false
[programs.localnet]
tiktok_clone = "9xyZ6LiwBCY4vfbeGqvso2sg8ohqczoDNhq7R2u3SoN1"

[registry]
url = "https://anchor.projectserum.com"

[provider]
#cluster = "devnet"
cluster = "localnet"

wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
start = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 app/start.ts"
